sudo: required
services:
    - docker 

before_install:
    - docker build -t dbcelm1/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dbcelm1/docker-react npm run test -- --coverage
    
    
