sudo: required
services:
    - docker 

before_install:
    - docker build -t dbcelm/docker-react -f Dockerfile.dev .

script:
    - docker run dbcelm/docker-react npm run test -- --coverage
    
    